"""
HTTPS & Security Settings:

- SECURE_SSL_REDIRECT: Redirect all HTTP traffic to HTTPS
- SECURE_HSTS_SECONDS: Enforce HTTPS in browsers for 1 year
- SECURE_HSTS_INCLUDE_SUBDOMAINS: Apply HSTS to all subdomains
- SECURE_HSTS_PRELOAD: Enable HSTS preload list
- SESSION_COOKIE_SECURE / CSRF_COOKIE_SECURE: Cookies sent only via HTTPS
- X_FRAME_OPTIONS: Prevent site from being framed (clickjacking protection)
- SECURE_CONTENT_TYPE_NOSNIFF: Prevent MIME sniffing
- SECURE_BROWSER_XSS_FILTER: Enable browser-side XSS filtering
"""


""" 
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--7)gze_$it^lj-lup@g@&!i7(5$iacgf3r93il%ui9=!jj=wt('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relashinship_app',
    'bookshelf.CustomUser',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'

# SECURITY SETTINGS

DEBUG = False  # Turn off in production to prevent sensitive info leakage

# Browser Security
SECURE_BROWSER_XSS_FILTER = True       # Prevents some XSS attacks
X_FRAME_OPTIONS = 'DENY'               # Prevents clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True     # Prevents MIME-type sniffing

# CSRF and Session Cookies
CSRF_COOKIE_SECURE = True              # Only sent over HTTPS
SESSION_COOKIE_SECURE = True           # Only sent over HTTPS

# Optional: Content Security Policy (CSP) header using middleware
# You can install django-csp for full CSP support
# pip install django-csp
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)

# HTTPS & HSTS Settings

# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000          # Enforce HTTPS for 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True   # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True              # Allows the site to be preloaded in browsers
