from django.urls import path
from .views import BookList

urlpatterns = [
    path('books/', BookList.as_view(), name='book-list'),
]

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from .views import BookList, BookViewSet


# ----------------------------
# ROUTER CONFIGURATION
# ----------------------------
# Automatically generates CRUD URLs for BookViewSet

router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')


# ----------------------------
# URL PATTERNS
# ----------------------------
urlpatterns = [
    # Public endpoint: list all books
    path('books/', BookList.as_view(), name='book-list'),

    # Token authentication endpoint
    # Users POST username & password here to receive a token
    path('token/', obtain_auth_token, name='api-token'),

    # All CRUD routes generated by the router
    path('', include(router.urls)),
]